spring:
  application:
    name: tikra-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tikra?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

  profiles:
    active: local
server:
  port: 8080
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.asus.tikra.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# AI
#langchain4j:
#  open-ai:
#    chat-model:
#      base-url: https://api.deepseek.com
#      api-key: <Your API Key>
#      model-name: deepseek-chat
#      max-tokens: 8192
#      log-requests: true
#      log-responses: true
#      # 流式响应
#    streaming-chat-model:
#      base-url: https://api.deepseek.com
#      api-key: <Your API Key>
#      model-name: deepseek-chat
#      max-tokens: 8192
#      log-requests: true
#      log-responses: true
